CREATE DATABASE IF NOT EXISTS bloc_1;
USE bloc_1;

-- Table USER
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

-- Table CITY
CREATE TABLE CITY (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50) NOT NULL UNIQUE
);

-- Table COMPANY_GOUV
CREATE TABLE COMPANY_GOUV (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    institution_address VARCHAR(255) NOT NULL,
    head_address VARCHAR(255) NOT NULL,
    longitude FLOAT NOT NULL,
    latitude FLOAT NOT NULL,
    city_ID INT NOT NULL,
    FOREIGN KEY (city_ID) REFERENCES CITY(id) ON DELETE CASCADE
);

-- Table COMPANY_PLANITY
CREATE TABLE COMPANY_PLANITY (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    institution_address VARCHAR(255) NOT NULL,
    city_ID INT NOT NULL,
    FOREIGN KEY (city_ID) REFERENCES CITY(id) ON DELETE CASCADE
);


